---
title: "Prac 9"
author: "Philip"
date: "2025-09-09"
output: html_document
---
```{r}
suppressPackageStartupMessages({
  library("seqinr") # is a package designed to process and analyse sequence data.
  library("R.utils") # general utilities like zip and unzip
})
```
```{r}
library("R.utils")

URL="http://ftp.ensemblgenomes.org/pub/bacteria/release-53/fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655_gca_000005845/cds/Escherichia_coli_str_k_12_substr_mg1655_gca_000005845.ASM584v2.cds.all.fa.gz"
download.file(URL,destfile="ecoli_cds.fa.gz")
gunzip("ecoli_cds.fa.gz")
list.files()
```

```{r}
library("seqinr")
```
```{r}
cds <- seqinr::read.fasta("ecoli_cds.fa")
str(head(cds))
```

```{r}
length(cds)
```

```{r}
head(summary(cds))
```

```{r}
len <- as.numeric(summary(cds)[,1])

sum(len)
```
```{r}
mean(len)
```
```{r}
median(len)
```
```{r}
```


```{r}
hist(len)
```
```{r}
GC(cds[[1]])
```
```{r}
count(cds[[1]],1)
```
```{r}
count(cds[[1]],3)
```
```{r}
length(unlist(cds[1:3]))
```
```{r}
GC(unlist(cds[1:3]))
```
```{r}
unlist(cds)->dna
```
```{r}
dna_composition <- count(dna,1)

barplot(dna_composition,xlab="nucleotides",ylab="frequency", main="E coli CDS composition")
```
```{r}
dna_composition/sum(dna_composition)
```
```{r}
barplot(dna_composition,xlab="nucleotides",ylab="proportion", main="E coli CDS composition")

grid()
```
```{r}
translate(cds[[1]])
```
```{r}
prot <- lapply(cds, translate)
```

```{r}

aa <- unique(prot[[2]])
aa <- aa[aa != "*"]
length(aa)
```
```{r}
count(prot[[1]],wordsize=1,alphabet=aa)
```

```{r}
count(prot[[2]],wordsize=1,alphabet=aa)
```
```{r}

library("seqinr")

proteome <- seqinr::read.fasta("ecoli_cds.fa")



all_proteins <- unlist(proteome)
mega_protein <- do.call(xscat, as.list(all_proteins))



```
```{r}
uco(cds[[2]])
```
```{r}
uco(cds[[2]],index="rscu")
```
```{r}
uco(cds[[2]],index="rscu",as.data.frame=TRUE)
```
```{r}
prots <- unlist(prot)

mycounts <- count(prots,wordsize=3,alphabet=aa)

str(mycounts)
```
```{r}
head(mycounts)
```
```{r}
myfreq <- count(prots,wordsize=3,alphabet=aa,freq=TRUE)

str(myfreq)
```
```{r}
sessionInfo()
```

